version: 2
formats: all

sphinx:
  configuration: docs/source/conf.py
  
python:
    version: 3
    install:
        - requirements: docs/source/requirements.txt
        - method: pip
          path: .