[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "ppsql"
authors = [{name = "lc06", email = "2546655793@qq"}]
dynamic = ["version", "description"]
